### ISSUE TITLE
FreeCameraController and OrbitCameraController

### ISSUE THREAD

**Issue by jiaxianghao** [Prograda/Skybolt#30]
Can you give me some examples of these two controllers? When I use the FreeCameraController, I find the screen is black.

**Comment by matthew-reid** [comment]
FreeCameraController is a "first person shooter" style camera where you control linear movement with W,A,S,D keys, and rotate with the mouse. The camera moves forwards/backwards/sideways relative to whatever direction you are looking in. The screen is most likely black because the camera is positioned somewhere either inside the earth, or far from the earth, or potentially not orientated to point at the earth.

OrbitCameraController is always focusing on the target, and "orbits" around the target by moving the mouse. It functions like a "3rd person view" in a flight simulator.

**Comment by jiaxianghao** [comment]
At present, all four operators can be used normally. Thank you.
